name = "Gendo"
uuid = "75c55192-876a-11e8-0f01-0fcedd69ab0f"
authors = ["Andrei Zhabinski <andrei.zhabinski@pandadoc.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
