name = "Yota"
uuid = "f7b0de00-8e67-11e8-1ba4-09bec8501be6"
authors = ["Andrei Zhabinski <andrei.zhabinski@pandadoc.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
